language: python
python: "3.5"
dist: trusty
sudo: true
install:
  - pip install -U setuptools
  # install_requires
  - pip install -U git+https://github.com/colcon/colcon-core
  - pip install -U git+https://github.com/colcon/colcon-library-path
  # tests_require
  - pip install -U flake8-blind-except flake8-builtins flake8-class-newline flake8-comprehensions flake8-deprecated flake8-docstrings flake8-quotes pep8-naming pyenchant pylint pytest pytest-cov
script:
  # invoke pytest
  - pytest --cov=colcon_cargo --cov-branch
notifications:
  email: false
